# Generated by Django 5.2.13 on 2026-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_data", "0005_alter_response_table_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student_fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Std_id", models.IntegerField()),
                ("Semester", models.CharField()),
                ("Fee_amount", models.IntegerField()),
                ("Paid_amt", models.IntegerField()),
                ("Due_amt", models.IntegerField()),
                (
                    "Payment_date_and_time",
                    models.DateField(verbose_name="Paymentd Date and time"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Studentdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Std_id", models.IntegerField()),
                ("Contact", models.IntegerField(max_length=10)),
                ("Email", models.EmailField(max_length=254)),
                ("Age", models.IntegerField()),
                ("Parents_Name", models.CharField(max_length=20)),
                ("Location", models.CharField()),
                ("Faculty", models.CharField()),
                ("Batch", models.DateField(verbose_name="Batch")),
            ],
        ),
    ]
