# Generated by Django 5.2.13 on 2026-04-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_data", "0006_student_fee_studentdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="Contact",
            field=models.IntegerField(),
        ),
    ]
