# Generated by Django 5.2.13 on 2026-04-27 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_data", "0007_alter_studentdetails_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student_fee",
            options={
                "ordering": ["-id"],
                "verbose_name": "Student Fee",
                "verbose_name_plural": "Student Fees",
            },
        ),
        migrations.AlterModelOptions(
            name="studentdetails",
            options={
                "ordering": ["-id"],
                "verbose_name": "Student Detail",
                "verbose_name_plural": "Student Details",
            },
        ),
        migrations.AlterModelTable(
            name="student_fee",
            table="student_fee",
        ),
        migrations.AlterModelTable(
            name="studentdetails",
            table="student_details",
        ),
    ]
