# Generated by Django 5.2.13 on 2026-04-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_data", "0008_alter_student_fee_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_fee",
            name="Std_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core_data.studentdetails",
            ),
        ),
    ]
