# Generated by Django 5.2.13 on 2026-04-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_data", "0009_alter_student_fee_std_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="Std_id",
            field=models.IntegerField(unique=True),
        ),
    ]
