# Generated by Django 5.2.13 on 2026-04-27 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_data", "0010_alter_studentdetails_std_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_fee",
            name="Name",
        ),
    ]
